export const COMBAT_TUNING = {
  enemyRatings: {
    'forest-rat': { accuracy: 6, defence: 4 },
    'goblin-scavenger': { accuracy: 15, defence: 12 },
    'cave-bat': { accuracy: 28, defence: 18 },
    'stoneback-crab': { accuracy: 30, defence: 40 },
    'grey-wolf': { accuracy: 55, defence: 42 },
    'road-bandit': { accuracy: 75, defence: 70 },
  },
  hitChanceMin: 0.35,
  hitChanceMax: 0.97,
  accurateAccuracyMultiplier: 1.15,
  aggressiveAccuracyMultiplier: 0.9,
  aggressiveMaxHitMultiplier: 1.1,
  defensiveDefenceMultiplier: 1.2,
  defensiveMaxHitMultiplier: 0.9,
  ratFirstAttackMultiplier: 0.65,
  goblinDesperateThreshold: 0.3,
  goblinDesperateMaxHitMultiplier: 1.4,
  batDefenceMultiplier: 1.35,
  crabFlatReduction: 2,
  wolfBleedChance: 0.3,
  wolfMaxBleedStacks: 3,
  wolfBleedDamagePerStack: 1,
  banditHeavyAttackEvery: 4,
  banditHeavyMaxHitMultiplier: 1.75,
  momentumMax: 100,
  momentumPerPlayerHit: 12,
  momentumPerDirectDamageTaken: 6,
  eliteSpawnChance: 0.05,
  eliteHealthMultiplier: 1.25,
  eliteGoldMultiplier: 1.25,
  eliteSavageMaxHitMultiplier: 1.35,
  eliteArmouredDefenceMultiplier: 1.35,
  eliteArmouredFlatReduction: 1,
  eliteSwiftIntervalMultiplier: 0.8,
  wealthyGoldMultiplier: 2.5,
  treasureTouchedLootMultiplier: 1.75,
  minimumAttackIntervalMs: 500,
  threatTrivial: 0.25,
  threatEasy: 0.6,
  threatFair: 1,
  threatDangerous: 1.8,
} as const;
