export const COMBAT_TUNING = {
  enemyRatings: {
    'redknife-lookout': { accuracy: 5, defence: 3 },
    'redknife-brigand': { accuracy: 8, defence: 6 },
    'redknife-bowhand': { accuracy: 11, defence: 7 },
    'redknife-enforcer': { accuracy: 12, defence: 12 },
    'greyfang-wolf': { accuracy: 12, defence: 10 },
    'greyfang-stalker': { accuracy: 15, defence: 13 },
    'greyfang-ravager': { accuracy: 18, defence: 15 },
    'greyfang-alpha': { accuracy: 21, defence: 19 },
    'brambletooth-scavenger': { accuracy: 18, defence: 16 },
    'brambletooth-spearman': { accuracy: 21, defence: 22 },
    'brambletooth-trapper': { accuracy: 24, defence: 18 },
    'brambletooth-boarhandler': { accuracy: 27, defence: 24 },
  },
  hitChanceMin: 0.35,
  hitChanceMax: 0.97,
  accurateAccuracyMultiplier: 1.15,
  aggressiveAccuracyMultiplier: 0.9,
  aggressiveMaxHitMultiplier: 1.1,
  defensiveDefenceMultiplier: 1.2,
  defensiveMaxHitMultiplier: 0.9,
  watchfulOpeningAttacks: 2,
  watchfulIntervalMultiplier: 0.6,
  /** @deprecated v15 tuning aliases retained for legacy test/save parsing. */
  ratFirstAttackMultiplier: 0.65,
  banditOpportunistAccuracyMultiplier: 1.15,
  scrappyMaxStacks: 5,
  scrappyIntervalMultiplierPerStack: 0.95,
  packHunterMaxStacks: 4,
  packHunterDamageMultiplierPerStack: 1.05,
  enemySpecialChargeMax: 100,
  enemySpecialChargePerNormalAttack: 25,
  enemySpecialChargePerDirectPlayerHitTaken: 5,
  adrenalineMax: 100,
  adrenalinePerPlayerHit: 12,
  adrenalinePerDirectDamageTaken: 6,
  eliteSpawnChance: 0.05,
  eliteHealthMultiplier: 1.25,
  eliteGoldMultiplier: 1.25,
  eliteSavageMaxHitMultiplier: 1.35,
  eliteArmouredDefenceMultiplier: 1.35,
  eliteArmouredFlatReduction: 1,
  eliteSwiftIntervalMultiplier: 0.8,
  wealthyGoldMultiplier: 2.5,
  treasureTouchedLootMultiplier: 1.75,
  minimumAttackIntervalMs: 500,
  /** Base health recovery while idle, mining, or smithing. Combat never recovers HP. */
  outOfCombatHealthRegenPercentPerSecond: 0.01,
  /** Health retained after a combat death before normal out-of-combat recovery resumes. */
  deathRecoveryHealthPercent: 0.25,
} as const;
