export const COMBAT_TUNING = {
  enemyRatings: {
    'forest-rat': { accuracy: 6, defence: 4 },
    'goblin-scavenger': { accuracy: 15, defence: 12 },
    'cave-bat': { accuracy: 28, defence: 18 },
    'stoneback-crab': { accuracy: 30, defence: 40 },
    'grey-wolf': { accuracy: 55, defence: 42 },
    'road-bandit': { accuracy: 75, defence: 70 },
    'hill-boar': { accuracy: 85, defence: 92 },
    'stonehide-ram': { accuracy: 92, defence: 110 },
    'tunnel-crawler': { accuracy: 104, defence: 84 },
    'forsaken-miner': { accuracy: 106, defence: 124 },
    'cliff-harpy': { accuracy: 116, defence: 142 },
    'stonehill-marauder': { accuracy: 120, defence: 114 },
    'ironbound-sentinel': { accuracy: 118, defence: 154 },
    'watchtower-captain': { accuracy: 134, defence: 146 },
  },
  hitChanceMin: 0.35,
  hitChanceMax: 0.97,
  accurateAccuracyMultiplier: 1.15,
  aggressiveAccuracyMultiplier: 0.9,
  aggressiveMaxHitMultiplier: 1.1,
  defensiveDefenceMultiplier: 1.2,
  defensiveMaxHitMultiplier: 0.9,
  ratFirstAttackMultiplier: 0.65,
  goblinDesperateThreshold: 0.3,
  goblinDesperateMaxHitMultiplier: 1.4,
  batDefenceMultiplier: 1.35,
  crabFlatReduction: 2,
  wolfBleedChance: 0.3,
  wolfMaxBleedStacks: 3,
  wolfBleedDamagePerStack: 1,
  banditOpportunistHealthThreshold: 0.5,
  banditOpportunistAccuracyMultiplier: 1.15,
  corneredFuryHealthThreshold: 0.35,
  corneredFuryDamageMultiplier: 1.15,
  corneredFuryAttackIntervalMultiplier: 0.8,
  stonehideFlatReduction: 3,
  bloodScentDamageMultiplier: 1.2,
  patchworkPlateFlatReduction: 4,
  elusiveFlightAdvanceFraction: 0.2,
  battleFuryIntervalMs: 10_000,
  battleFuryMaxStacks: 5,
  battleFuryDamageMultiplier: 1.05,
  reinforcedPlatingFlatReduction: 5,
  reinforcedPlatingHealthThreshold: 0.5,
  reinforcedPlatingDefenceMultiplier: 1.2,
  lastStandHealthThreshold: 0.4,
  lastStandAccuracyMultiplier: 1.2,
  lastStandAttackIntervalMultiplier: 0.8,
  enemySpecialChargeMax: 100,
  enemySpecialChargePerNormalAttack: 25,
  enemySpecialChargePerDirectPlayerHitTaken: 5,
  adrenalineMax: 100,
  adrenalinePerPlayerHit: 12,
  adrenalinePerDirectDamageTaken: 6,
  eliteSpawnChance: 0.05,
  eliteHealthMultiplier: 1.25,
  eliteGoldMultiplier: 1.25,
  eliteSavageMaxHitMultiplier: 1.35,
  eliteArmouredDefenceMultiplier: 1.35,
  eliteArmouredFlatReduction: 1,
  eliteSwiftIntervalMultiplier: 0.8,
  wealthyGoldMultiplier: 2.5,
  treasureTouchedLootMultiplier: 1.75,
  minimumAttackIntervalMs: 500,
  /** Base health recovery while idle, mining, or smithing. Combat never recovers HP. */
  outOfCombatHealthRegenPercentPerSecond: 0.01,
  /** Health retained after a combat death before normal out-of-combat recovery resumes. */
  deathRecoveryHealthPercent: 0.25,
} as const;
