import type { AreaDefinition } from '../game/types';

export const AREAS: AreaDefinition[] = [
  {
    id: 'forest-path',
    regionId: 'greenvale',
    name: 'Forest Path',
    description: 'A woodland trail where the frontier gives way to tangled green.',
    identity: 'Woodland Trail',
    requiredCombatLevel: 1,
    enemyIds: ['forest-rat', 'goblin-scavenger'],
    accent: '#b58b53',
    recommendedLevel: [1, 8],
    presentation: { iconKey: 'tree', theme: 'forest-path', environmentKey: 'forest-path' },
  },
  {
    id: 'wolf-den',
    regionId: 'greenvale',
    name: 'Wolf Den',
    description: 'A cold hollow beneath the pines, marked by old tracks and watchful eyes.',
    identity: 'Predator Den',
    requiredCombatLevel: 18,
    enemyIds: ['grey-wolf'],
    accent: '#71839a',
    recommendedLevel: [18, 28],
    presentation: { iconKey: 'tree', theme: 'wolf-den', environmentKey: 'wolf-den' },
  },
  {
    id: 'abandoned-camp',
    regionId: 'greenvale',
    name: 'Abandoned Camp',
    description: 'A weathered campsite where the fire is cold but the outlaws are not.',
    identity: 'Outlaw Camp',
    requiredCombatLevel: 24,
    enemyIds: ['road-bandit'],
    accent: '#a47b5f',
    recommendedLevel: [24, 35],
    presentation: { iconKey: 'target', theme: 'abandoned-camp', environmentKey: 'abandoned-camp' },
  },
  {
    id: 'old-shrine',
    regionId: 'greenvale',
    name: 'Old Shrine',
    description: 'Ruined stone and a forgotten altar draw creatures from the dark.',
    identity: 'Ancient Ruins',
    requiredCombatLevel: 8,
    enemyIds: ['cave-bat', 'stoneback-crab'],
    accent: '#7d748d',
    recommendedLevel: [8, 18],
    presentation: { iconKey: 'crystal', theme: 'old-shrine', environmentKey: 'old-shrine' },
  },
  {
    id: 'rocky-foothills',
    regionId: 'stonehill',
    name: 'Rocky Foothills',
    description: 'Broken slopes and exposed ridges where hardened beasts roam between old stone tracks.',
    identity: 'Windswept Uplands',
    requiredCombatLevel: 34,
    enemyIds: ['hill-boar', 'stonehide-ram'],
    accent: '#9a856a',
    recommendedLevel: [34, 40],
    presentation: { iconKey: 'mountain', theme: 'old-shrine', environmentKey: 'old-shrine' },
  },
  {
    id: 'abandoned-mine',
    regionId: 'stonehill',
    name: 'Abandoned Mine',
    description: 'Old Stonehill shafts filled with abandoned tools, crawling things, and miners who never truly left.',
    identity: 'Collapsed Workings',
    requiredCombatLevel: 40,
    enemyIds: ['tunnel-crawler', 'forsaken-miner'],
    accent: '#756c66',
    recommendedLevel: [40, 47],
    presentation: { iconKey: 'crystal', theme: 'old-shrine', environmentKey: 'old-shrine' },
  },
  {
    id: 'mountain-pass',
    regionId: 'stonehill',
    name: 'Mountain Pass',
    description: 'A narrow road cut through the heights, watched from above and preyed upon by raiders.',
    identity: 'High Road',
    requiredCombatLevel: 47,
    enemyIds: ['cliff-harpy', 'stonehill-marauder'],
    accent: '#7f8790',
    recommendedLevel: [47, 54],
    presentation: { iconKey: 'mountain', theme: 'wolf-den', environmentKey: 'wolf-den' },
  },
  {
    id: 'ruined-watchtower',
    regionId: 'stonehill',
    name: 'Ruined Watchtower',
    description: 'A fortified ruin still guarded by iron sentinels and the soldiers who claimed it.',
    identity: 'Fallen Garrison',
    requiredCombatLevel: 54,
    enemyIds: ['ironbound-sentinel', 'watchtower-captain'],
    accent: '#8a8278',
    recommendedLevel: [54, 62],
    presentation: { iconKey: 'target', theme: 'abandoned-camp', environmentKey: 'abandoned-camp' },
  },
];

export const areaById = Object.fromEntries(AREAS.map((area) => [area.id, area]));
