import type { CombatEffectDefinition } from '../game/types';

/** Central definitions for every combat effect that can appear in a live encounter. */
export const COMBAT_EFFECTS: CombatEffectDefinition[] = [
  {
    id: 'bleeding',
    name: 'Bleeding',
    polarity: 'debuff',
    description: 'Takes periodic damage as the bleeding wears off.',
    durationMs: null,
    maxStacks: 3,
    stacking: 'stack',
    tags: ['bleed'],
    periodicDamage: { intervalMs: 2_000, damagePerStack: 1, ignoresDefence: true },
  },
  {
    id: 'desperate-swing',
    name: 'Desperate Swing',
    polarity: 'buff',
    description: 'The enemy deals heavier damage while badly wounded.',
    durationMs: null,
    stacking: 'refresh',
  },
  {
    id: 'defence-rend',
    name: 'Defence Rend',
    polarity: 'debuff',
    description: 'Reduces Defence for a short time.',
    durationMs: 8_000,
    stacking: 'refresh',
    modifiers: { defenceMultiplier: 0.85 },
  },
  {
    id: 'enemy-damage-up',
    name: 'Empowered Damage',
    polarity: 'buff',
    description: 'Increases outgoing damage.',
    durationMs: 8_000,
    stacking: 'refresh',
    modifiers: { damageMultiplier: 1.2 },
  },
  {
    id: 'enemy-defence-up',
    name: 'Hardened Defence',
    polarity: 'buff',
    description: 'Increases Defence.',
    durationMs: 8_000,
    stacking: 'refresh',
    modifiers: { defenceMultiplier: 1.2 },
  },
  {
    id: 'enemy-attack-speed-up',
    name: 'Hastened',
    polarity: 'buff',
    description: 'Shortens the attack interval.',
    durationMs: 8_000,
    stacking: 'refresh',
    modifiers: { attackIntervalMultiplier: 0.8 },
  },
  {
    id: 'enemy-damage-defence-up',
    name: 'Battle Trance',
    polarity: 'buff',
    description: 'Increases outgoing damage and Defence.',
    durationMs: 8_000,
    stacking: 'refresh',
    modifiers: { damageMultiplier: 1.15, defenceMultiplier: 1.15 },
  },
  {
    id: 'cornered-fury',
    name: 'Cornered Fury',
    polarity: 'buff',
    description: 'While badly wounded, deals 15% more damage and attacks 25% faster.',
    durationMs: null,
    stacking: 'refresh',
    modifiers: { damageMultiplier: 1.15, attackIntervalMultiplier: 0.8 },
  },
  {
    id: 'stunned',
    name: 'Stunned',
    polarity: 'debuff',
    description: 'The next attack is delayed while the stun lasts.',
    durationMs: 1_250,
    stacking: 'refresh',
  },
  {
    id: 'rending-bleed',
    name: 'Rending Bleed',
    polarity: 'debuff',
    description: 'Bleeds for 2 damage per stack every 2 seconds.',
    durationMs: 8_000,
    maxStacks: 2,
    stacking: 'stack',
    tags: ['bleed'],
    periodicDamage: { intervalMs: 2_000, damagePerStack: 2, ignoresDefence: true },
  },
  {
    id: 'armour-broken',
    name: 'Armour Broken',
    polarity: 'debuff',
    description: 'Reduces Defence by 25% for 8 seconds.',
    durationMs: 8_000,
    stacking: 'refresh',
    modifiers: { defenceMultiplier: 0.75 },
  },
  {
    id: 'raking-wound',
    name: 'Raking Wound',
    polarity: 'debuff',
    description: 'Bleeds for 2 damage every 2 seconds.',
    durationMs: 10_000,
    maxStacks: 1,
    stacking: 'refresh',
    tags: ['bleed'],
    periodicDamage: { intervalMs: 2_000, damagePerStack: 2, ignoresDefence: true },
  },
  {
    id: 'blood-scent',
    name: 'Blood Scent',
    polarity: 'buff',
    description: 'Deals 20% more damage while the player is bleeding.',
    durationMs: null,
    stacking: 'refresh',
    modifiers: { damageMultiplier: 1.2 },
  },
  {
    id: 'battle-fury',
    name: 'Battle Fury',
    polarity: 'buff',
    description: 'Gains 5% damage per stack every 10 seconds, up to 5 stacks.',
    durationMs: null,
    maxStacks: 5,
    stacking: 'stack',
    modifiers: { damageMultiplier: 1.05 },
  },
  {
    id: 'war-cry',
    name: 'War Cry',
    polarity: 'buff',
    description: 'Increases damage by 25% and attack speed by 15% for 8 seconds.',
    durationMs: 8_000,
    stacking: 'refresh',
    modifiers: { damageMultiplier: 1.25, attackIntervalMultiplier: 0.85 },
  },
  {
    id: 'fortified',
    name: 'Fortified',
    polarity: 'buff',
    description: 'Increases Defence by 40% for 8 seconds.',
    durationMs: 8_000,
    stacking: 'refresh',
    modifiers: { defenceMultiplier: 1.4 },
  },
  {
    id: 'reinforced-plating',
    name: 'Reinforced Plating',
    polarity: 'buff',
    description: 'While above 50% Health, reduces incoming damage and increases Defence by 20%.',
    durationMs: null,
    stacking: 'refresh',
    modifiers: { defenceMultiplier: 1.2, flatDamageReduction: 5 },
  },
  {
    id: 'last-stand',
    name: 'Last Stand',
    polarity: 'buff',
    description: 'While badly wounded, gains 20% Accuracy and attacks 25% faster.',
    durationMs: null,
    stacking: 'refresh',
    modifiers: { accuracyMultiplier: 1.2, attackIntervalMultiplier: 0.8 },
  },
  {
    id: 'iron-command',
    name: 'Iron Command',
    polarity: 'buff',
    description: 'Increases damage by 25% and Defence by 25% for 10 seconds.',
    durationMs: 10_000,
    stacking: 'refresh',
    modifiers: { damageMultiplier: 1.25, defenceMultiplier: 1.25 },
  },
];

export const combatEffectById: Record<string, CombatEffectDefinition> = Object.fromEntries(
  COMBAT_EFFECTS.map((effect) => [effect.id, effect]),
);
