import type { CombatEffectDefinition } from '../game/types';

/** Definitions for effects that may appear in a live Tauraque encounter. */
export const COMBAT_EFFECTS: CombatEffectDefinition[] = [
  {
    id: 'serrated-bleed',
    kind: 'bleed',
    name: 'Serrated Bleed',
    polarity: 'debuff',
    description: 'Takes 1 damage per stack every 2 seconds.',
    durationMs: 8_000,
    maxStacks: 2,
    stacking: 'stack',
    periodicDamage: { intervalMs: 2_000, damagePerStack: 1, ignoresDefence: true },
  },
  {
    id: 'crippled',
    kind: 'attack-speed-debuff',
    name: 'Crippled',
    polarity: 'debuff',
    description: "Player Attack Interval is increased by 25%.",
    durationMs: 6_000,
    stacking: 'refresh',
    modifiers: { attackIntervalMultiplier: 1.25 },
  },
  {
    id: 'rending-bleed',
    kind: 'bleed',
    name: 'Rending Bleed',
    polarity: 'debuff',
    description: 'Takes 1 damage per stack every 2 seconds.',
    durationMs: 6_000,
    maxStacks: 2,
    stacking: 'stack',
    periodicDamage: { intervalMs: 2_000, damagePerStack: 1, ignoresDefence: true },
  },
  {
    id: 'savage-bleed',
    kind: 'bleed',
    name: 'Savage Bleed',
    polarity: 'debuff',
    description: 'Takes 2 damage every 2 seconds.',
    durationMs: 8_000,
    maxStacks: 1,
    stacking: 'refresh',
    periodicDamage: { intervalMs: 2_000, damagePerStack: 2, ignoresDefence: true },
  },
  {
    id: 'throat-wound',
    kind: 'bleed',
    name: 'Throat Wound',
    polarity: 'debuff',
    description: 'Takes 2 damage every 2 seconds.',
    durationMs: 10_000,
    maxStacks: 1,
    stacking: 'refresh',
    periodicDamage: { intervalMs: 2_000, damagePerStack: 2, ignoresDefence: true },
  },
  {
    id: 'dazed',
    kind: 'accuracy-debuff',
    name: 'Dazed',
    polarity: 'debuff',
    description: 'Player Accuracy is reduced by 20%.',
    durationMs: 6_000,
    stacking: 'refresh',
    modifiers: { accuracyMultiplier: 0.8 },
  },
  {
    id: 'stunned',
    kind: 'stun',
    name: 'Stunned',
    polarity: 'debuff',
    description: 'The next attack is delayed while the stun lasts.',
    durationMs: 1_250,
    stacking: 'refresh',
  },
];

export const combatEffectById: Record<string, CombatEffectDefinition> = Object.fromEntries(
  COMBAT_EFFECTS.map((effect) => [effect.id, effect]),
);
