import { COMBAT_TUNING } from '../config/combatTuning';
import type { EnemyDefinition, EnemyId, EnemySpecialDefinition, EnemyTraitId, LootEntry } from '../game/types';

const special = (
  id: string,
  name: string,
  description: string,
  damageMultiplier: number,
  accuracyMultiplier: number,
  effects: EnemySpecialDefinition['effects'] = [],
  conditional?: Pick<EnemySpecialDefinition, 'playerHealthThreshold' | 'conditionalDamageMultiplier'>,
): EnemySpecialDefinition => ({
  id,
  name,
  description,
  delivery: 'attack',
  damageMultiplier,
  accuracyMultiplier,
  effects,
  ...conditional,
});

const trait = (id: EnemyTraitId, name: string, description: string) => ({ id, name, description });
const signature = (itemId: string, chance: number): LootEntry => ({ itemId, chance, min: 1, max: 1 });
const presentation = (
  archetype: 'bandit' | 'wolf' | 'goblin',
  primaryColor: string,
  secondaryColor: string,
  scale = 1,
): EnemyDefinition['presentation'] => ({
  archetype,
  primaryColor,
  secondaryColor,
  scale,
  idleAnimation: archetype === 'wolf' ? 'alert' : archetype === 'goblin' ? 'hunch' : 'stride',
  attackAnimation: archetype === 'wolf' ? 'pounce' : archetype === 'goblin' ? 'swipe' : 'slash',
});

const enemy = (
  id: EnemyId,
  name: string,
  description: string,
  areaId: EnemyDefinition['areaId'],
  displayLevel: number,
  maxHealth: number,
  attackIntervalMs: number,
  maxHit: number,
  traitDefinition: EnemyDefinition['trait'],
  specialAttack: EnemySpecialDefinition,
  signatureLoot: LootEntry,
  accuracyRating: number,
  defenceRating: number,
  theme: EnemyDefinition['theme'],
  enemyPresentation: EnemyDefinition['presentation'],
): EnemyDefinition => ({
  id,
  name,
  description,
  areaId,
  displayLevel,
  maxHealth,
  attackIntervalMs,
  maxHit,
  accuracyRating,
  defenceRating,
  trait: traitDefinition,
  specialAttack,
  signatureLoot,
  theme,
  presentation: enemyPresentation,
});

const r = COMBAT_TUNING.enemyRatings;

export const ENEMIES: EnemyDefinition[] = [
  enemy(
    'redknife-lookout',
    'Redknife Lookout',
    "A lightly equipped bandit responsible for watching Lornwick's roads and warning the camp.",
    'redknife-road-camp',
    1,
    14,
    2_800,
    2,
    trait('watchful', 'Watchful', 'The Lookout begins combat ready. Its first two attacks are 40% faster.'),
    special('quick-jab', 'Quick Jab', 'A quick, carefully placed jab with greatly increased Accuracy.', 1, 1.5),
    signature('lookouts-sapphire-ring', 0.01),
    r['redknife-lookout'].accuracy,
    r['redknife-lookout'].defence,
    'bandit',
    presentation('bandit', '#a47b5f', '#302b2c', 0.9),
  ),
  enemy(
    'redknife-brigand',
    'Redknife Brigand',
    'A standard Redknife melee fighter accustomed to ambushing travellers.',
    'redknife-road-camp',
    3,
    22,
    2_800,
    3,
    trait('dirty-fighter', 'Dirty Fighter', 'Deals 20% more damage to afflicted targets.'),
    special('serrated-slash', 'Serrated Slash', 'A jagged slash that causes a stacking Bleed.', 1.1, 1.05, [
      { kind: 'apply-combat-effect', effectId: 'serrated-bleed', target: 'player', applyOn: 'hit' },
    ]),
    signature('redknife-cape', 0.008),
    r['redknife-brigand'].accuracy,
    r['redknife-brigand'].defence,
    'bandit',
    presentation('bandit', '#9a674f', '#302b2c', 0.96),
  ),
  enemy(
    'redknife-bowhand',
    'Redknife Bowhand',
    'A ranged faction specialist using a hunting bow from cover.',
    'redknife-road-camp',
    5,
    30,
    3_000,
    3,
    trait('precise', 'Precise', 'Carefully aimed attacks gain 20% Accuracy.'),
    special('crippling-shot', 'Crippling Shot', "An accurate shot that slows the player's attacks for a short time.", 0.9, 1.35, [
      { kind: 'apply-combat-effect', effectId: 'crippled', target: 'player', applyOn: 'hit' },
    ]),
    signature('redknife-hunting-bow', 0.008),
    r['redknife-bowhand'].accuracy,
    r['redknife-bowhand'].defence,
    'bandit',
    presentation('bandit', '#b07d5a', '#302b2c', 0.94),
  ),
  enemy(
    'redknife-enforcer',
    'Redknife Enforcer',
    'A heavily built Redknife used when intimidation and brute force are required.',
    'redknife-road-camp',
    7,
    42,
    3_400,
    4,
    trait('heavy-hitter', 'Heavy Hitter', 'Attacks more slowly, but its normal and Special hits are substantially heavier.'),
    special('crushing-blow', 'Crushing Blow', 'A heavy strike that hits much harder and is more reliable against defensive targets.', 1.6, 1.2),
    signature('redknife-reinforced-greatsword', 0.005),
    r['redknife-enforcer'].accuracy,
    r['redknife-enforcer'].defence,
    'bandit',
    presentation('bandit', '#80604d', '#282526', 1.08),
  ),
  enemy(
    'greyfang-wolf',
    'Greyfang Wolf',
    'A normal adult member of the Greyfang pack.',
    'greyfang-pastures',
    4,
    36,
    2_500,
    3,
    trait('pack-hunter', 'Pack Hunter', 'Consecutive hits build hunting momentum, increasing damage by 5% per stack up to four stacks. Missing resets the momentum.'),
    special('rending-bite', 'Rending Bite', 'A tearing bite that causes a stacking Bleed.', 1, 1.1, [
      { kind: 'apply-combat-effect', effectId: 'rending-bleed', target: 'player', applyOn: 'hit' },
    ]),
    signature('pristine-wolf-pelt', 0.015),
    r['greyfang-wolf'].accuracy,
    r['greyfang-wolf'].defence,
    'wolf',
    presentation('wolf', '#7f909b', '#3e4d56', 1.02),
  ),
  enemy(
    'greyfang-stalker',
    'Greyfang Stalker',
    'A lean, cautious hunter specialized in avoiding retaliation.',
    'greyfang-pastures',
    6,
    46,
    2_200,
    4,
    trait('evasive', 'Evasive', 'Erratic movement increases Defence by 25%.'),
    special('pouncing-strike', 'Pouncing Strike', 'A sudden pounce with greatly increased Accuracy.', 1.15, 1.5),
    signature('stalkers-claw', 0.01),
    r['greyfang-stalker'].accuracy,
    r['greyfang-stalker'].defence,
    'wolf',
    presentation('wolf', '#788d9d', '#364650', 1.04),
  ),
  enemy(
    'greyfang-ravager',
    'Greyfang Ravager',
    'A larger and more aggressive pack member.',
    'greyfang-pastures',
    8,
    60,
    2_600,
    5,
    trait('ferocious', 'Ferocious', 'Below 40% Health, damage increases by 20%.'),
    special('savage-maul', 'Savage Maul', 'A brutal mauling attack that causes a stronger short-duration Bleed.', 1.4, 1.05, [
      { kind: 'apply-combat-effect', effectId: 'savage-bleed', target: 'player', applyOn: 'hit' },
    ]),
    signature('ravager-fang', 0.008),
    r['greyfang-ravager'].accuracy,
    r['greyfang-ravager'].defence,
    'wolf',
    presentation('wolf', '#687c87', '#33424b', 1.08),
  ),
  enemy(
    'greyfang-alpha',
    'Greyfang Alpha',
    'The strongest repeatable Greyfang target in the Area, but not a boss.',
    'greyfang-pastures',
    10,
    78,
    2_400,
    6,
    trait('apex-predator', 'Apex Predator', 'Deals 20% more damage to wounded targets below half Health.'),
    special('throat-lunge', 'Throat Lunge', 'Lunges for the throat, causing a severe Bleed and dealing much more damage to critically wounded targets.', 1.3, 1.15, [
      { kind: 'apply-combat-effect', effectId: 'throat-wound', target: 'player', applyOn: 'hit' },
    ], { playerHealthThreshold: 0.35, conditionalDamageMultiplier: 1.5 }),
    signature('greyfang-trophy', 0.005),
    r['greyfang-alpha'].accuracy,
    r['greyfang-alpha'].defence,
    'wolf',
    presentation('wolf', '#5d717b', '#2c3a42', 1.14),
  ),
  enemy(
    'brambletooth-scavenger',
    'Brambletooth Scavenger',
    'A low-ranking goblin gathering stolen goods, scrap, and discarded equipment.',
    'brambletooth-camp',
    7,
    55,
    2_500,
    4,
    trait('scrappy', 'Scrappy', 'While above half Health, taking direct hits builds Scrappy stacks. Each stack makes it attack 5% faster, up to five stacks. All stacks are lost at half Health.'),
    special('scrap-toss', 'Scrap Toss', 'Hurls jagged scrap, dealing light damage and reducing Accuracy.', 0.85, 1.2, [
      { kind: 'apply-combat-effect', effectId: 'dazed', target: 'player', applyOn: 'hit' },
    ]),
    signature('scavengers-dagger', 0.01),
    r['brambletooth-scavenger'].accuracy,
    r['brambletooth-scavenger'].defence,
    'goblin',
    presentation('goblin', '#668356', '#354733', 0.94),
  ),
  enemy(
    'brambletooth-spearman',
    'Brambletooth Spearman',
    'An organized goblin fighter using a crude spear and guarded stance.',
    'brambletooth-camp',
    9,
    70,
    3_000,
    5,
    trait('cautious-fighter', 'Cautious Fighter', 'A guarded stance increases Defence by 25%.'),
    special('jagged-thrust', 'Jagged Thrust', 'A carefully placed spear thrust with greatly increased Accuracy.', 1.2, 1.5),
    signature('jagged-goblin-spear', 0.008),
    r['brambletooth-spearman'].accuracy,
    r['brambletooth-spearman'].defence,
    'goblin',
    presentation('goblin', '#6e8b58', '#344931', 1),
  ),
  enemy(
    'brambletooth-trapper',
    'Brambletooth Trapper',
    'A hunter and trapper using snares and opportunistic attacks.',
    'brambletooth-camp',
    11,
    85,
    2_700,
    5,
    trait('opportunist', 'Opportunist', 'Deals 20% more damage to afflicted targets.'),
    special('snaring-throw', 'Snaring Throw', "A crude snare delays the player's next attack by 75% of its normal interval.", 0.7, 1.25, [
      { kind: 'player-attack-delay-fraction', fractionOfAttackInterval: 0.75, applyOn: 'hit' },
    ]),
    signature('trappers-knife', 0.008),
    r['brambletooth-trapper'].accuracy,
    r['brambletooth-trapper'].defence,
    'goblin',
    presentation('goblin', '#5f7c4f', '#30432e', 1.02),
  ),
  enemy(
    'brambletooth-boarhandler',
    'Brambletooth Boarhandler',
    'A stronger goblin trained to control domesticated war boars.',
    'brambletooth-camp',
    13,
    110,
    3_200,
    7,
    trait('beast-handler', 'Beast Handler', 'Fighting alongside a trained beast lets the Boarhandler maintain 20% faster attacks.'),
    special('boar-charge', 'Boar Charge', "Commands a trained boar to charge, dealing heavy damage and knocking back the player's attack progress.", 1.5, 1.15, [
      { kind: 'player-attack-progress-pushback', fractionOfAttackInterval: 0.5, applyOn: 'hit' },
    ]),
    signature('boarhandlers-harness', 0.005),
    r['brambletooth-boarhandler'].accuracy,
    r['brambletooth-boarhandler'].defence,
    'goblin',
    presentation('goblin', '#587448', '#2e402d', 1.1),
  ),
];

export const enemyById = Object.fromEntries(ENEMIES.map((enemy) => [enemy.id, enemy])) as Record<string, EnemyDefinition>;
