import type { EnemyDefinition } from '../game/types';

export const ENEMIES: EnemyDefinition[] = [
  {
    id: 'forest-rat',
    name: 'Forest Rat',
    description: 'A bold scavenger with more grit than size.',
    areaId: 'training-grounds',
    displayLevel: 1,
    maxHealth: 12,
    attackIntervalMs: 2600,
    maxHit: 2,
    loot: [
      { itemId: 'rat-tail', chance: 0.25, min: 1, max: 1 },
      { itemId: 'tattered-hide', chance: 0.18, min: 1, max: 1 },
    ],
    gold: [1, 4],
    theme: 'rodent',
    tags: ['Beast', 'Fast', 'Weak'],
  },
  {
    id: 'goblin-scavenger',
    name: 'Goblin Scavenger',
    description: 'A scrappy raider guarding the road into the hills.',
    areaId: 'training-grounds',
    displayLevel: 4,
    maxHealth: 25,
    attackIntervalMs: 2800,
    maxHit: 4,
    loot: [
      { itemId: 'goblin-scrap', chance: 0.55, min: 1, max: 1 },
      { itemId: 'tattered-hide', chance: 0.2, min: 1, max: 1 },
    ],
    gold: [3, 8],
    theme: 'goblin',
    tags: ['Humanoid', 'Scavenger'],
  },
  {
    id: 'cave-bat',
    name: 'Cave Bat',
    description: 'A quick-winged predator in the copper galleries.',
    areaId: 'copper-hills',
    displayLevel: 10,
    maxHealth: 110,
    attackIntervalMs: 2200,
    maxHit: 9,
    loot: [{ itemId: 'bat-wing', chance: 0.58, min: 1, max: 1 }],
    gold: [8, 16],
    theme: 'bat',
    tags: ['Beast', 'Flying', 'Fast'],
  },
  {
    id: 'stoneback-crab',
    name: 'Stoneback Crab',
    description: 'A living boulder with a stubborn temper.',
    areaId: 'copper-hills',
    displayLevel: 14,
    maxHealth: 180,
    attackIntervalMs: 3400,
    maxHit: 13,
    loot: [{ itemId: 'crab-shell', chance: 0.48, min: 1, max: 1 }],
    gold: [10, 22],
    theme: 'crab',
    tags: ['Beast', 'Armored', 'Slow'],
  },
  {
    id: 'grey-wolf',
    name: 'Grey Wolf',
    description: 'A patient hunter on the pass through the ironwood.',
    areaId: 'ironwood-pass',
    displayLevel: 24,
    maxHealth: 300,
    attackIntervalMs: 2400,
    maxHit: 19,
    loot: [{ itemId: 'wolf-pelt', chance: 0.52, min: 1, max: 1 }],
    gold: [20, 40],
    theme: 'wolf',
    tags: ['Beast', 'Fast'],
  },
  {
    id: 'road-bandit',
    name: 'Road Bandit',
    description: 'An armored outlaw who knows every trail marker.',
    areaId: 'ironwood-pass',
    displayLevel: 30,
    maxHealth: 430,
    attackIntervalMs: 3000,
    maxHit: 24,
    loot: [
      { itemId: 'bandit-token', chance: 0.44, min: 1, max: 1 },
      { itemId: 'rusted-emblem', chance: 0.12, min: 1, max: 1 },
    ],
    gold: [28, 60],
    theme: 'bandit',
    tags: ['Humanoid', 'Armored'],
  },
];

export const enemyById = Object.fromEntries(ENEMIES.map((enemy) => [enemy.id, enemy]));
