import type { EnemyDefinition } from '../game/types';
import { COMBAT_TUNING } from '../config/combatTuning';

export const ENEMIES: EnemyDefinition[] = [
  {
    id: 'forest-rat',
    name: 'Forest Rat',
    description: 'A bold scavenger with more grit than size.',
    areaId: 'forest-path',
    displayLevel: 1,
    maxHealth: 12,
    attackIntervalMs: 2600,
    maxHit: 2,
    accuracyRating: COMBAT_TUNING.enemyRatings['forest-rat'].accuracy,
    defenceRating: COMBAT_TUNING.enemyRatings['forest-rat'].defence,
    trait: {
      id: 'scurry',
      name: 'Scurry',
      description: 'Its first attack arrives sooner than normal.',
    },
    loot: [
      { itemId: 'rat-tail', chance: 0.25, min: 1, max: 1 },
      { itemId: 'tattered-hide', chance: 0.18, min: 1, max: 1 },
    ],
    gold: [1, 4],
    theme: 'rodent',
    presentation: {
      archetype: 'rat',
      primaryColor: '#9b765b',
      secondaryColor: '#4b3530',
      scale: 0.72,
      idleAnimation: 'scurry',
      attackAnimation: 'lunge',
    },
  },
  {
    id: 'goblin-scavenger',
    name: 'Goblin Scavenger',
    description: 'A scrappy raider guarding the road into the hills.',
    areaId: 'forest-path',
    displayLevel: 4,
    maxHealth: 25,
    attackIntervalMs: 2800,
    maxHit: 4,
    accuracyRating: COMBAT_TUNING.enemyRatings['goblin-scavenger'].accuracy,
    defenceRating: COMBAT_TUNING.enemyRatings['goblin-scavenger'].defence,
    trait: {
      id: 'desperate-swing',
      name: 'Desperate Swing',
      description: 'Deals heavier damage while below 30% Health.',
    },
    loot: [
      { itemId: 'goblin-scrap', chance: 0.55, min: 1, max: 1 },
      { itemId: 'tattered-hide', chance: 0.2, min: 1, max: 1 },
    ],
    gold: [3, 8],
    theme: 'goblin',
    presentation: {
      archetype: 'goblin',
      primaryColor: '#668356',
      secondaryColor: '#354733',
      scale: 0.92,
      idleAnimation: 'hunch',
      attackAnimation: 'swipe',
    },
  },
  {
    id: 'cave-bat',
    name: 'Cave Bat',
    description: 'A quick-winged predator in the copper galleries.',
    areaId: 'old-shrine',
    displayLevel: 10,
    maxHealth: 110,
    attackIntervalMs: 2200,
    maxHit: 9,
    accuracyRating: COMBAT_TUNING.enemyRatings['cave-bat'].accuracy,
    defenceRating: COMBAT_TUNING.enemyRatings['cave-bat'].defence,
    trait: {
      id: 'evasive',
      name: 'Evasive',
      description: 'Its erratic movement greatly increases Defence.',
    },
    loot: [{ itemId: 'bat-wing', chance: 0.58, min: 1, max: 1 }],
    gold: [8, 16],
    theme: 'bat',
    presentation: {
      archetype: 'bat',
      primaryColor: '#7c6891',
      secondaryColor: '#302744',
      scale: 0.82,
      idleAnimation: 'hover',
      attackAnimation: 'swoop',
    },
  },
  {
    id: 'stoneback-crab',
    name: 'Stoneback Crab',
    description: 'A living boulder with a stubborn temper.',
    areaId: 'old-shrine',
    displayLevel: 14,
    maxHealth: 180,
    attackIntervalMs: 3400,
    maxHit: 13,
    accuracyRating: COMBAT_TUNING.enemyRatings['stoneback-crab'].accuracy,
    defenceRating: COMBAT_TUNING.enemyRatings['stoneback-crab'].defence,
    trait: {
      id: 'armoured-shell',
      name: 'Armoured Shell',
      description: 'Reduces damage from each successful hit.',
    },
    loot: [{ itemId: 'crab-shell', chance: 0.48, min: 1, max: 1 }],
    gold: [10, 22],
    theme: 'crab',
    presentation: {
      archetype: 'crab',
      primaryColor: '#a06b4d',
      secondaryColor: '#51372d',
      scale: 1.08,
      idleAnimation: 'heavy',
      attackAnimation: 'claw',
    },
  },
  {
    id: 'grey-wolf',
    name: 'Grey Wolf',
    description: 'A patient hunter on the pass through the ironwood.',
    areaId: 'wolf-den',
    displayLevel: 24,
    maxHealth: 300,
    attackIntervalMs: 2400,
    maxHit: 19,
    accuracyRating: COMBAT_TUNING.enemyRatings['grey-wolf'].accuracy,
    defenceRating: COMBAT_TUNING.enemyRatings['grey-wolf'].defence,
    trait: {
      id: 'bleeding-bites',
      name: 'Bleeding Bites',
      description: 'Successful attacks can cause stacking damage over time.',
    },
    loot: [{ itemId: 'wolf-pelt', chance: 0.52, min: 1, max: 1 }],
    gold: [20, 40],
    theme: 'wolf',
    presentation: {
      archetype: 'wolf',
      primaryColor: '#7f909b',
      secondaryColor: '#3e4d56',
      scale: 1.1,
      idleAnimation: 'alert',
      attackAnimation: 'pounce',
    },
  },
  {
    id: 'road-bandit',
    name: 'Road Bandit',
    description: 'An armored outlaw who knows every trail marker.',
    areaId: 'abandoned-camp',
    displayLevel: 30,
    maxHealth: 430,
    attackIntervalMs: 3000,
    maxHit: 24,
    accuracyRating: COMBAT_TUNING.enemyRatings['road-bandit'].accuracy,
    defenceRating: COMBAT_TUNING.enemyRatings['road-bandit'].defence,
    trait: {
      id: 'opportunist',
      name: 'Opportunist',
      description: 'Becomes more accurate against badly wounded opponents.',
    },
    specialAttack: {
      id: 'heavy-strike',
      name: 'Heavy Strike',
      description: 'A powerful attack that hits harder and more accurately.',
      delivery: 'attack',
      damageMultiplier: 1.75,
      accuracyMultiplier: 1.25,
      effects: [],
    },
    loot: [
      { itemId: 'bandit-token', chance: 0.44, min: 1, max: 1 },
      { itemId: 'rusted-emblem', chance: 0.12, min: 1, max: 1 },
    ],
    gold: [28, 60],
    theme: 'bandit',
    presentation: {
      archetype: 'bandit',
      primaryColor: '#a47b5f',
      secondaryColor: '#302b2c',
      scale: 0.98,
      idleAnimation: 'stride',
      attackAnimation: 'slash',
    },
  },
  {
    id: 'hill-boar',
    name: 'Hill Boar',
    description: 'A broad-shouldered boar hardened by wind, stone, and narrow trails.',
    areaId: 'rocky-foothills',
    displayLevel: 34,
    maxHealth: 520,
    attackIntervalMs: 3200,
    maxHit: 27,
    accuracyRating: COMBAT_TUNING.enemyRatings['hill-boar'].accuracy,
    defenceRating: COMBAT_TUNING.enemyRatings['hill-boar'].defence,
    trait: {
      id: 'cornered-fury',
      name: 'Cornered Fury',
      description: 'Below 35% Health, gains 15% damage and attacks 25% faster once per encounter.',
    },
    specialAttack: {
      id: 'goring-charge',
      name: 'Goring Charge',
      description: 'A brutal charge that hits harder and pushes the player attack backwards.',
      delivery: 'attack',
      damageMultiplier: 1.5,
      accuracyMultiplier: 1.25,
      effects: [{ kind: 'player-attack-progress-pushback', fractionOfAttackInterval: 0.4, applyOn: 'hit' }],
    },
    loot: [
      { itemId: 'coarse-boar-hide', chance: 0.55, min: 1, max: 1 },
      { itemId: 'boar-tusk', chance: 0.3, min: 1, max: 1 },
      { itemId: 'stonehill-bristle', chance: 0.14, min: 1, max: 1 },
    ],
    theme: 'wolf',
    presentation: {
      archetype: 'wolf',
      primaryColor: '#806b59',
      secondaryColor: '#3f3028',
      scale: 1.12,
      idleAnimation: 'heavy',
      attackAnimation: 'pounce',
    },
  },
  {
    id: 'stonehide-ram',
    name: 'Stonehide Ram',
    description: 'A mountain ram whose hide is thick enough to turn aside a careless blow.',
    areaId: 'rocky-foothills',
    displayLevel: 38,
    maxHealth: 610,
    attackIntervalMs: 3500,
    maxHit: 30,
    accuracyRating: COMBAT_TUNING.enemyRatings['stonehide-ram'].accuracy,
    defenceRating: COMBAT_TUNING.enemyRatings['stonehide-ram'].defence,
    trait: {
      id: 'stonehide',
      name: 'Stonehide',
      description: 'Reduces damage from each successful hit by 3.',
    },
    specialAttack: {
      id: 'skullbreaker',
      name: 'Skullbreaker',
      description: 'A crushing headbutt that delays the player and briefly stuns them on hit.',
      delivery: 'attack',
      damageMultiplier: 1.35,
      accuracyMultiplier: 1.35,
      effects: [
        { kind: 'player-attack-delay', amountMs: 1250, applyOn: 'hit' },
        { kind: 'apply-combat-effect', effectId: 'stunned', target: 'player', applyOn: 'hit' },
      ],
    },
    loot: [
      { itemId: 'stonewool-fleece', chance: 0.5, min: 1, max: 1 },
      { itemId: 'ram-horn', chance: 0.3, min: 1, max: 1 },
      { itemId: 'dense-hoof-fragment', chance: 0.16, min: 1, max: 1 },
    ],
    theme: 'wolf',
    presentation: {
      archetype: 'wolf',
      primaryColor: '#a49c8d',
      secondaryColor: '#504b45',
      scale: 1.15,
      idleAnimation: 'heavy',
      attackAnimation: 'pounce',
    },
  },
  {
    id: 'tunnel-crawler',
    name: 'Tunnel Crawler',
    description: 'A many-legged crawler that follows the scent of fresh blood through the dark.',
    areaId: 'abandoned-mine',
    displayLevel: 41,
    maxHealth: 500,
    attackIntervalMs: 1700,
    maxHit: 20,
    accuracyRating: COMBAT_TUNING.enemyRatings['tunnel-crawler'].accuracy,
    defenceRating: COMBAT_TUNING.enemyRatings['tunnel-crawler'].defence,
    trait: {
      id: 'blood-scent',
      name: 'Blood Scent',
      description: 'Deals 20% more damage while the player has a bleed effect.',
    },
    specialAttack: {
      id: 'rending-bite',
      name: 'Rending Bite',
      description: 'A tearing bite that applies a stacking bleed on hit.',
      delivery: 'attack',
      damageMultiplier: 1,
      accuracyMultiplier: 1.2,
      effects: [{ kind: 'apply-combat-effect', effectId: 'rending-bleed', target: 'player', applyOn: 'hit' }],
    },
    loot: [
      { itemId: 'crawler-carapace', chance: 0.5, min: 1, max: 1 },
      { itemId: 'burrow-claw', chance: 0.28, min: 1, max: 1 },
      { itemId: 'glow-sac', chance: 0.12, min: 1, max: 1 },
    ],
    theme: 'crab',
    presentation: {
      archetype: 'crab',
      primaryColor: '#687b72',
      secondaryColor: '#283d39',
      scale: 1.04,
      idleAnimation: 'scurry',
      attackAnimation: 'claw',
    },
  },
  {
    id: 'forsaken-miner',
    name: 'Forsaken Miner',
    description: 'A lost miner in patched armor, still guarding a claim abandoned years ago.',
    areaId: 'abandoned-mine',
    displayLevel: 45,
    maxHealth: 730,
    attackIntervalMs: 2800,
    maxHit: 31,
    accuracyRating: COMBAT_TUNING.enemyRatings['forsaken-miner'].accuracy,
    defenceRating: COMBAT_TUNING.enemyRatings['forsaken-miner'].defence,
    trait: {
      id: 'patchwork-plate',
      name: 'Patchwork Plate',
      description: 'Reduces damage from each successful hit by 4.',
    },
    specialAttack: {
      id: 'armor-break',
      name: 'Armor Break',
      description: 'A precise strike that reduces the player’s Defence on hit.',
      delivery: 'attack',
      damageMultiplier: 1.25,
      accuracyMultiplier: 1.15,
      effects: [{ kind: 'apply-combat-effect', effectId: 'armour-broken', target: 'player', applyOn: 'hit' }],
    },
    loot: [
      { itemId: 'bent-pick-head', chance: 0.46, min: 1, max: 1 },
      { itemId: 'miners-badge', chance: 0.26, min: 1, max: 1 },
      { itemId: 'blackened-lantern', chance: 0.14, min: 1, max: 1 },
      { itemId: 'old-claim-token', chance: 0.07, min: 1, max: 1 },
    ],
    gold: [34, 68],
    theme: 'bandit',
    presentation: {
      archetype: 'bandit',
      primaryColor: '#777066',
      secondaryColor: '#302e2b',
      scale: 1,
      idleAnimation: 'hunch',
      attackAnimation: 'slash',
    },
  },
  {
    id: 'cliff-harpy',
    name: 'Cliff Harpy',
    description: 'A sharp-eyed harpy nesting above the pass, quick to exploit every missed blow.',
    areaId: 'mountain-pass',
    displayLevel: 48,
    maxHealth: 620,
    attackIntervalMs: 2100,
    maxHit: 27,
    accuracyRating: COMBAT_TUNING.enemyRatings['cliff-harpy'].accuracy,
    defenceRating: COMBAT_TUNING.enemyRatings['cliff-harpy'].defence,
    trait: {
      id: 'elusive-flight',
      name: 'Elusive Flight',
      description: 'Whenever the player misses, advances its next attack by 20% of its interval.',
    },
    specialAttack: {
      id: 'raking-dive',
      name: 'Raking Dive',
      description: 'A plunging attack that applies a lasting bleed on hit.',
      delivery: 'attack',
      damageMultiplier: 1.4,
      accuracyMultiplier: 1.3,
      effects: [{ kind: 'apply-combat-effect', effectId: 'raking-wound', target: 'player', applyOn: 'hit' }],
    },
    loot: [
      { itemId: 'harpy-feather', chance: 0.52, min: 1, max: 1 },
      { itemId: 'hooked-talon', chance: 0.28, min: 1, max: 1 },
      { itemId: 'windworn-pinion', chance: 0.14, min: 1, max: 1 },
      { itemId: 'cliff-nest-trinket', chance: 0.06, min: 1, max: 1 },
    ],
    theme: 'bat',
    presentation: {
      archetype: 'bat',
      primaryColor: '#9a7f9f',
      secondaryColor: '#3b2e48',
      scale: 0.95,
      idleAnimation: 'hover',
      attackAnimation: 'swoop',
    },
  },
  {
    id: 'stonehill-marauder',
    name: 'Stonehill Marauder',
    description: 'A seasoned raider who turns every long fight into another advantage.',
    areaId: 'mountain-pass',
    displayLevel: 52,
    maxHealth: 820,
    attackIntervalMs: 2500,
    maxHit: 34,
    accuracyRating: COMBAT_TUNING.enemyRatings['stonehill-marauder'].accuracy,
    defenceRating: COMBAT_TUNING.enemyRatings['stonehill-marauder'].defence,
    trait: {
      id: 'battle-fury',
      name: 'Battle Fury',
      description: 'Every 10 seconds gains a stack, increasing damage by 5%, up to 5 stacks.',
    },
    specialAttack: {
      id: 'war-cry',
      name: 'War Cry',
      description: 'Consumes an attack to increase damage and attack speed for 8 seconds.',
      delivery: 'self',
      effects: [{ kind: 'apply-combat-effect', effectId: 'war-cry', target: 'enemy', applyOn: 'always' }],
    },
    loot: [
      { itemId: 'marauder-insignia', chance: 0.42, min: 1, max: 1 },
      { itemId: 'riveted-leather-scrap', chance: 0.32, min: 1, max: 1 },
      { itemId: 'warband-token', chance: 0.16, min: 1, max: 1 },
      { itemId: 'notched-whetstone', chance: 0.08, min: 1, max: 1 },
    ],
    gold: [48, 90],
    theme: 'bandit',
    presentation: {
      archetype: 'bandit',
      primaryColor: '#8b5f4c',
      secondaryColor: '#31282a',
      scale: 1.03,
      idleAnimation: 'stride',
      attackAnimation: 'slash',
    },
  },
  {
    id: 'ironbound-sentinel',
    name: 'Ironbound Sentinel',
    description: 'An iron guardian that has kept its post long after the watchtower fell.',
    areaId: 'ruined-watchtower',
    displayLevel: 56,
    maxHealth: 1050,
    attackIntervalMs: 3300,
    maxHit: 35,
    accuracyRating: COMBAT_TUNING.enemyRatings['ironbound-sentinel'].accuracy,
    defenceRating: COMBAT_TUNING.enemyRatings['ironbound-sentinel'].defence,
    trait: {
      id: 'reinforced-plating',
      name: 'Reinforced Plating',
      description: 'Reduces damage by 5 and gains 20% Defence while above 50% Health.',
    },
    specialAttack: {
      id: 'fortify',
      name: 'Fortify',
      description: 'Consumes an attack to increase Defence by 40% for 8 seconds.',
      delivery: 'self',
      effects: [{ kind: 'apply-combat-effect', effectId: 'fortified', target: 'enemy', applyOn: 'always' }],
    },
    loot: [
      { itemId: 'sentinel-plate-fragment', chance: 0.48, min: 1, max: 1 },
      { itemId: 'rusted-gear', chance: 0.34, min: 1, max: 1 },
      { itemId: 'runed-rivet', chance: 0.16, min: 1, max: 1 },
      { itemId: 'watchtower-core', chance: 0.06, min: 1, max: 1 },
    ],
    theme: 'bandit',
    presentation: {
      archetype: 'bandit',
      primaryColor: '#777d84',
      secondaryColor: '#30363b',
      scale: 1.08,
      idleAnimation: 'heavy',
      attackAnimation: 'slash',
    },
  },
  {
    id: 'watchtower-captain',
    name: 'Watchtower Captain',
    description: 'A fallen captain still issuing orders from a ruined stone parapet.',
    areaId: 'ruined-watchtower',
    displayLevel: 60,
    maxHealth: 1220,
    attackIntervalMs: 2600,
    maxHit: 39,
    accuracyRating: COMBAT_TUNING.enemyRatings['watchtower-captain'].accuracy,
    defenceRating: COMBAT_TUNING.enemyRatings['watchtower-captain'].defence,
    trait: {
      id: 'last-stand',
      name: 'Last Stand',
      description: 'Below 40% Health, gains 20% Accuracy and attacks 25% faster once per encounter.',
    },
    specialAttack: {
      id: 'iron-command',
      name: 'Iron Command',
      description: 'Consumes an attack to increase damage and Defence for 10 seconds.',
      delivery: 'self',
      effects: [{ kind: 'apply-combat-effect', effectId: 'iron-command', target: 'enemy', applyOn: 'always' }],
    },
    loot: [
      { itemId: 'captains-sigil', chance: 0.42, min: 1, max: 1 },
      { itemId: 'watchtower-key-fragment', chance: 0.26, min: 1, max: 1 },
      { itemId: 'commanders-strap', chance: 0.14, min: 1, max: 1 },
      { itemId: 'old-garrison-seal', chance: 0.06, min: 1, max: 1 },
    ],
    gold: [75, 130],
    theme: 'bandit',
    presentation: {
      archetype: 'bandit',
      primaryColor: '#9c7860',
      secondaryColor: '#342b2c',
      scale: 1.06,
      idleAnimation: 'stride',
      attackAnimation: 'slash',
    },
  },
];

export const enemyById = Object.fromEntries(ENEMIES.map((enemy) => [enemy.id, enemy]));
