import type { ItemCategory, ItemDefinition, WeaponSpecial } from '../game/types';

const material = (
  id: string,
  name: string,
  description: string,
  source: string,
): ItemDefinition => ({
  id,
  name,
  category: 'material',
  description,
  source,
  stackable: true,
  rarity: 'common',
  presentation: { iconKey: 'ore', visualCategory: 'material' },
});
const bar = (id: string, name: string, description: string, source: string): ItemDefinition => ({
  id,
  name,
  category: 'bar',
  description,
  source,
  stackable: true,
  rarity: 'common',
  presentation: { iconKey: 'bar', visualCategory: 'metal' },
});
const gear = (
  id: string,
  name: string,
  slot: ItemDefinition['slot'],
  tier: ItemDefinition['tier'],
  bonuses: NonNullable<ItemDefinition['bonuses']>,
  level: string,
  specialAttack?: WeaponSpecial,
  description?: string,
  categoryOverride?: Extract<ItemCategory, 'weapon' | 'armor' | 'shield' | 'tool'>,
): ItemDefinition => ({
  id,
  name,
  category: categoryOverride ?? (slot === 'weapon' ? 'weapon' : slot === 'tool' ? 'tool' : 'armor'),
  description: description ?? `${level} ${slot} forged for dependable field work.`,
  source: 'Smithing',
  stackable: true,
  rarity: tier === 'steel' ? 'rare' : tier === 'iron' ? 'uncommon' : 'common',
  presentation: {
    iconKey:
      categoryOverride === 'shield'
        ? 'shield'
        : categoryOverride === 'tool' || slot === 'tool'
          ? 'tool'
          : categoryOverride === 'weapon' || slot === 'weapon'
            ? 'sword'
            : 'armor',
    visualCategory: 'equipment',
  },
  slot,
  tier,
  bonuses,
  weaponHands: slot === 'weapon' ? 1 : undefined,
  specialAttack,
});

const ALL_ITEMS: ItemDefinition[] = [
  material(
    'stone-ore',
    'Stone Ore',
    'A versatile stone resource for future fieldwork and production.',
    'Mining Â· Stone Outcrop',
  ),
  {
    id: 'rough-gem',
    name: 'Rough Gem',
    category: 'material',
    description: 'A raw stone with a glint worth saving.',
    source: 'Mining',
    stackable: true,
    rarity: 'rare',
    presentation: { iconKey: 'gem', visualCategory: 'material' },
  },
  material('iron-ore', 'Iron Ore', 'Dense ore that takes a dark polish.', 'Mining Â· Iron Vein'),
  material('coal', 'Coal Ore', 'Dense fuel ore for a hotter, cleaner forge.', 'Mining Â· Coal Seam'),
  bar('iron-bar', 'Iron Bar', 'A strong foundation for practical gear.', 'Smithing Â· Smelting'),
  bar('steel-bar', 'Steel Bar', 'Coal-hardened iron for elite gear.', 'Smithing Â· Smelting'),
  {
    id: 'worn-pickaxe',
    name: 'Worn Pickaxe',
    category: 'tool',
    description: 'A serviceable starter pick with a blunt but honest edge.',
    source: 'Mining',
    stackable: true,
    rarity: 'common',
    presentation: { iconKey: 'tool', visualCategory: 'equipment' },
    slot: 'tool',
    bonuses: {},
  },
  gear(
    'iron-sword',
    'Iron Sword',
    'weapon',
    'iron',
    { attack: 18, strength: 12, attackSpeed: 0.05 },
    'Iron',
    {
      id: 'sundering-strike',
      name: 'Sundering Strike',
      description: 'A heavy blow that breaks through flat damage reduction.',
      damageMultiplier: 1.75,
      accuracyMultiplier: 1.15,
      ignoresFlatDamageReduction: true,
    },
  ),
  gear('iron-helmet', 'Iron Helm', 'head', 'iron', { defence: 12, health: 6 }, 'Iron'),
  gear(
    'iron-armor',
    'Iron Armor',
    'armor',
    'iron',
    { defence: 38, health: 18 },
    'Iron',
    undefined,
    'A complete iron field harness built for sustained combat.',
  ),
  gear(
    'iron-shield',
    'Iron Bulwark',
    'offhand',
    'iron',
    { defence: 24, health: 8 },
    'Iron',
    undefined,
    undefined,
    'shield',
  ),
  gear('iron-pickaxe', 'Iron Pick', 'tool', 'iron', {}, 'Iron'),
  {
    ...gear('iron-smithing-hammer', 'Iron Smithing Hammer', 'tool', 'iron', {}, 'Iron'),
    source: 'Smithing Â· Anvil',
    description: 'A balanced hammer that speeds Anvil work and occasionally preserves a bar.',
  },
  gear(
    'steel-sword',
    'Steel Sword',
    'weapon',
    'steel',
    { attack: 32, strength: 24, attackSpeed: 0.1 },
    'Steel',
    {
      id: 'executioners-cut',
      name: "Executioner's Cut",
      description: 'Deals greatly increased damage to wounded enemies.',
      damageMultiplier: 1.75,
      accuracyMultiplier: 1.1,
      executeThreshold: 0.35,
      executeDamageMultiplier: 2.25,
    },
  ),
  gear('steel-helmet', 'Steel Helm', 'head', 'steel', { defence: 21, health: 10 }, 'Steel'),
  gear(
    'steel-armor',
    'Steel Armor',
    'armor',
    'steel',
    { defence: 67, health: 32 },
    'Steel',
    undefined,
    'A complete steel field harness forged for the harshest frontiers.',
  ),
  gear(
    'steel-shield',
    'Steel Bulwark',
    'offhand',
    'steel',
    { defence: 42, health: 14 },
    'Steel',
    undefined,
    undefined,
    'shield',
  ),
  gear('steel-pickaxe', 'Steel Pick', 'tool', 'steel', {}, 'Steel'),
  {
    ...gear('steel-smithing-hammer', 'Steel Smithing Hammer', 'tool', 'steel', {}, 'Steel'),
    source: 'Smithing Â· Anvil',
    description: 'A rare, carefully balanced hammer for fast and economical Anvil work.',
  },
  {
    id: 'black-stone', name: 'Black Stone', category: 'material', rarity: 'rare', stackable: true,
    description: 'A dense universal material reserved for future equipment enhancement.', source: 'Tauraque Â· Combat',
    presentation: { iconKey: 'ore', visualCategory: 'material' },
  },
  {
    id: 'magic-crystal-box', name: 'Magic Crystal Box', category: 'drop', rarity: 'rare', stackable: true,
    description: 'A sealed container for future character crystals.', source: 'Tauraque Â· Combat',
    presentation: { iconKey: 'crystal', visualCategory: 'creature-part' },
  },
  ...[
    ['redknife-token', 'Redknife Token', 'An uncommon Redknife marker for future faction systems.', 'uncommon', 'Tauraque Â· Lornwick Vale Â· Redknife Road Camp Â· All targets'],
    ['torn-cloth', 'Torn Cloth', 'A common strip of cloth salvaged from Redknife gear.', 'common', 'Tauraque Â· Lornwick Vale Â· Redknife Road Camp Â· All targets'],
    ['leather-scraps', 'Leather Scraps', 'Rough scraps set aside for future leatherworking.', 'common', 'Tauraque Â· Lornwick Vale Â· Redknife Road Camp Â· All targets'],
    ['iron-metal-scraps', 'Iron Metal Scraps', 'Recovered iron fragments awaiting future smithing use.', 'common', 'Tauraque Â· Lornwick Vale Â· Redknife Road Camp Â· All targets'],
    ['raw-wolf-meat', 'Raw Wolf Meat', 'Fresh meat from the Greyfang pastures.', 'common', 'Tauraque Â· Lornwick Vale Â· Greyfang Pastures Â· All targets'],
    ['vial-of-wolf-blood', 'Vial of Wolf Blood', 'A carefully stoppered vial of Greyfang blood.', 'uncommon', 'Tauraque Â· Lornwick Vale Â· Greyfang Pastures Â· All targets'],
    ['wolf-pelt', 'Wolf Pelt', 'A common pelt from the Greyfang pack.', 'common', 'Tauraque Â· Lornwick Vale Â· Greyfang Pastures Â· All targets'],
    ['wolf-fang', 'Wolf Fang', 'A sharp fang from a Greyfang predator.', 'uncommon', 'Tauraque Â· Lornwick Vale Â· Greyfang Pastures Â· All targets'],
    ['trace-of-nature', 'Trace of Nature', 'A rare nature-aligned material found in Greyfang territory.', 'rare', 'Tauraque Â· Lornwick Vale Â· Greyfang Pastures Â· All targets'],
    ['goblin-scrap', 'Goblin Scrap', 'A common Brambletooth field discovery.', 'common', 'Tauraque Â· Lornwick Vale Â· Brambletooth Camp Â· All targets'],
    ['frayed-cloth', 'Frayed Cloth', 'Crude cloth salvaged from goblin gear.', 'common', 'Tauraque Â· Lornwick Vale Â· Brambletooth Camp Â· All targets'],
    ['rough-leather', 'Rough Leather', 'Unworked leather from the Brambletooth camp.', 'common', 'Tauraque Â· Lornwick Vale Â· Brambletooth Camp Â· All targets'],
    ['small-coin-pouch', 'Small Coin Pouch', 'A sealed pouch reserved for a future opening system.', 'uncommon', 'Tauraque Â· Lornwick Vale Â· Brambletooth Camp Â· All targets'],
  ].map(([id, name, description, rarity, source]) => ({
    id, name, category: id === 'goblin-scrap' || id === 'small-coin-pouch' ? 'drop' as const : 'material' as const,
    description, source, stackable: true, rarity: rarity as 'common' | 'uncommon' | 'rare',
    presentation: { iconKey: 'creature-part', visualCategory: 'creature-part' },
  } as ItemDefinition)),
  ...[
    ['lookouts-sapphire-ring', "Lookout's Sapphire Ring", 'ring', { attack: 2, defence: 1 }, "Tauraque Â· Lornwick Vale Â· Redknife Road Camp Â· Redknife Lookout"],
    ['redknife-cape', 'Redknife Cape', 'cape', { defence: 2, health: 4 }, "Tauraque Â· Lornwick Vale Â· Redknife Road Camp Â· Redknife Brigand"],
    ['redknife-hunting-bow', 'Redknife Hunting Bow', null, {}, "Tauraque Â· Lornwick Vale Â· Redknife Road Camp Â· Redknife Bowhand"],
    ['redknife-reinforced-greatsword', 'Redknife Reinforced Greatsword', 'weapon', { attack: 21, strength: 15, attackSpeed: -0.04 }, "Tauraque Â· Lornwick Vale Â· Redknife Road Camp Â· Redknife Enforcer"],
    ['pristine-wolf-pelt', 'Pristine Wolf Pelt', null, {}, "Tauraque Â· Lornwick Vale Â· Greyfang Pastures Â· Greyfang Wolf"],
    ['stalkers-claw', "Stalker's Claw", null, {}, "Tauraque Â· Lornwick Vale Â· Greyfang Pastures Â· Greyfang Stalker"],
    ['ravager-fang', 'Ravager Fang', null, {}, "Tauraque Â· Lornwick Vale Â· Greyfang Pastures Â· Greyfang Ravager"],
    ['greyfang-trophy', 'Greyfang Trophy', null, {}, "Tauraque Â· Lornwick Vale Â· Greyfang Pastures Â· Greyfang Alpha"],
    ['scavengers-dagger', "Scavenger's Dagger", 'weapon', { attack: 13, strength: 7, attackSpeed: 0.12 }, "Tauraque Â· Lornwick Vale Â· Brambletooth Camp Â· Brambletooth Scavenger"],
    ['jagged-goblin-spear', 'Jagged Goblin Spear', 'weapon', { attack: 20, strength: 14, attackSpeed: -0.02 }, "Tauraque Â· Lornwick Vale Â· Brambletooth Camp Â· Brambletooth Spearman"],
    ['trappers-knife', "Trapper's Knife", 'weapon', { attack: 16, strength: 9, attackSpeed: 0.15 }, "Tauraque Â· Lornwick Vale Â· Brambletooth Camp Â· Brambletooth Trapper"],
    ['boarhandlers-harness', "Boarhandler's Harness", 'armor', { defence: 30, health: 14 }, "Tauraque Â· Lornwick Vale Â· Brambletooth Camp Â· Brambletooth Boarhandler"],
  ].map(([id, name, slot, bonuses, source]) => ({
    id, name, category: slot === 'weapon' ? 'weapon' as const : slot === 'armor' ? 'armor' as const : 'drop' as const,
    description: slot ? `A rare Tauraque ${slot} recovered from its signature owner.` : 'A rare signature discovery from Lornwick Vale.',
    source, stackable: true, rarity: 'rare' as const,
    presentation: { iconKey: slot ? (slot === 'weapon' ? 'sword' : 'armor') : 'creature-part', visualCategory: 'equipment' },
    ...(slot ? { slot, bonuses, ...(slot === 'weapon' ? { weaponHands: id === 'redknife-reinforced-greatsword' || id === 'jagged-goblin-spear' ? 2 as const : 1 as const } : {}) } : {}),
  } as ItemDefinition)),
];

export const ACTIVE_ITEMS: ItemDefinition[] = ALL_ITEMS;
export const ITEMS = ACTIVE_ITEMS;

export const itemById = Object.fromEntries(ITEMS.map((item) => [item.id, item])) as Record<
  string,
  ItemDefinition
>;
