import type { ItemCategory, ItemDefinition, WeaponSpecial } from '../game/types';

const material = (
  id: string,
  name: string,
  description: string,
  source: string,
): ItemDefinition => ({
  id,
  name,
  category: 'material',
  description,
  source,
  stackable: true,
  rarity: 'common',
  presentation: { iconKey: 'ore', visualCategory: 'material' },
});
const bar = (id: string, name: string, description: string, source: string): ItemDefinition => ({
  id,
  name,
  category: 'bar',
  description,
  source,
  stackable: true,
  rarity: 'common',
  presentation: { iconKey: 'bar', visualCategory: 'metal' },
});
const gear = (
  id: string,
  name: string,
  slot: ItemDefinition['slot'],
  tier: ItemDefinition['tier'],
  bonuses: NonNullable<ItemDefinition['bonuses']>,
  level: string,
  specialAttack?: WeaponSpecial,
  description?: string,
  categoryOverride?: Extract<ItemCategory, 'weapon' | 'armor' | 'shield' | 'tool'>,
): ItemDefinition => ({
  id,
  name,
  category: categoryOverride ?? (slot === 'weapon' ? 'weapon' : slot === 'tool' ? 'tool' : 'armor'),
  description: description ?? `${level} ${slot} forged for dependable field work.`,
  source: 'Smithing',
  stackable: true,
  rarity: tier === 'steel' ? 'rare' : tier === 'iron' ? 'uncommon' : 'common',
  presentation: {
    iconKey:
      categoryOverride === 'shield'
        ? 'shield'
        : categoryOverride === 'tool' || slot === 'tool'
          ? 'tool'
          : categoryOverride === 'weapon' || slot === 'weapon'
            ? 'sword'
            : 'armor',
    visualCategory: 'equipment',
  },
  slot,
  tier,
  bonuses,
  specialAttack,
});

export const ITEMS: ItemDefinition[] = [
  material(
    'stone-ore',
    'Stone Ore',
    'A versatile stone resource for future fieldwork and production.',
    'Mining · Stone Outcrop',
  ),
  {
    id: 'stone-fragment',
    name: 'Stone Fragment',
    category: 'material',
    description: 'Common chips shaken loose from worked rock.',
    source: 'Mining',
    stackable: true,
    rarity: 'common',
    presentation: { iconKey: 'ore', visualCategory: 'material' },
  },
  {
    id: 'sharpening-grit',
    name: 'Sharpening Grit',
    category: 'material',
    description: 'Abrasive mineral reserved for future tool work.',
    source: 'Mining',
    stackable: true,
    rarity: 'uncommon',
    presentation: { iconKey: 'ore', visualCategory: 'material' },
  },
  {
    id: 'rough-gem',
    name: 'Rough Gem',
    category: 'material',
    description: 'A raw stone with a glint worth saving.',
    source: 'Mining',
    stackable: true,
    rarity: 'rare',
    presentation: { iconKey: 'gem', visualCategory: 'material' },
  },
  material(
    'copper-ore',
    'Copper Ore',
    'Warm orange ore from shallow veins.',
    'Mining · Copper Vein',
  ),
  material('tin-ore', 'Tin Ore', 'Soft grey ore used with copper.', 'Mining · Tin Vein'),
  material('iron-ore', 'Iron Ore', 'Dense ore that takes a dark polish.', 'Mining · Iron Vein'),
  material('coal', 'Coal Ore', 'Dense fuel ore for a hotter, cleaner forge.', 'Mining · Coal Seam'),
  material(
    'mithril-ore',
    'Mithril Ore',
    'A preview mineral from deeper strata.',
    'Mining · Mithril Deposit',
  ),
  bar('bronze-bar', 'Bronze Bar', 'A reliable copper-tin alloy.', 'Smithing · Smelting'),
  bar('iron-bar', 'Iron Bar', 'A strong foundation for practical gear.', 'Smithing · Smelting'),
  bar('steel-bar', 'Steel Bar', 'Coal-hardened iron for elite gear.', 'Smithing · Smelting'),
  gear(
    'bronze-sword',
    'Bronze Sword',
    'weapon',
    'bronze',
    { attack: 8, strength: 5, attackSpeed: 0 },
    'Bronze',
    {
      id: 'focused-slash',
      name: 'Focused Slash',
      description: 'A controlled strike with increased damage and accuracy.',
      damageMultiplier: 1.6,
      accuracyMultiplier: 1.25,
    },
  ),
  gear('bronze-helmet', 'Bronze Helm', 'head', 'bronze', { defence: 5, health: 2 }, 'Bronze'),
  gear(
    'bronze-armor',
    'Bronze Armor',
    'armor',
    'bronze',
    { defence: 16, health: 7 },
    'Bronze',
    undefined,
    'A complete bronze field harness covering the torso and lower body.',
  ),
  gear(
    'bronze-shield',
    'Bronze Buckler',
    'offhand',
    'bronze',
    { defence: 10, health: 3 },
    'Bronze',
    undefined,
    undefined,
    'shield',
  ),
  {
    id: 'worn-pickaxe',
    name: 'Worn Pickaxe',
    category: 'tool',
    description: 'A serviceable starter pick with a blunt but honest edge.',
    source: 'Mining',
    stackable: true,
    rarity: 'common',
    presentation: { iconKey: 'tool', visualCategory: 'equipment' },
    slot: 'tool',
    bonuses: {},
  },
  gear('bronze-pickaxe', 'Bronze Pick', 'tool', 'bronze', {}, 'Bronze'),
  gear(
    'iron-sword',
    'Iron Sword',
    'weapon',
    'iron',
    { attack: 18, strength: 12, attackSpeed: 0.05 },
    'Iron',
    {
      id: 'sundering-strike',
      name: 'Sundering Strike',
      description: 'A heavy blow that breaks through flat damage reduction.',
      damageMultiplier: 1.75,
      accuracyMultiplier: 1.15,
      ignoresFlatDamageReduction: true,
    },
  ),
  gear('iron-helmet', 'Iron Helm', 'head', 'iron', { defence: 12, health: 6 }, 'Iron'),
  gear(
    'iron-armor',
    'Iron Armor',
    'armor',
    'iron',
    { defence: 38, health: 18 },
    'Iron',
    undefined,
    'A complete iron field harness built for sustained combat.',
  ),
  gear(
    'iron-shield',
    'Iron Bulwark',
    'offhand',
    'iron',
    { defence: 24, health: 8 },
    'Iron',
    undefined,
    undefined,
    'shield',
  ),
  gear('iron-pickaxe', 'Iron Pick', 'tool', 'iron', {}, 'Iron'),
  {
    ...gear('iron-smithing-hammer', 'Iron Smithing Hammer', 'tool', 'iron', {}, 'Iron'),
    source: 'Smithing · Anvil',
    description: 'A balanced hammer that speeds Anvil work and occasionally preserves a bar.',
  },
  gear(
    'steel-sword',
    'Steel Sword',
    'weapon',
    'steel',
    { attack: 32, strength: 24, attackSpeed: 0.1 },
    'Steel',
    {
      id: 'executioners-cut',
      name: "Executioner's Cut",
      description: 'Deals greatly increased damage to wounded enemies.',
      damageMultiplier: 1.75,
      accuracyMultiplier: 1.1,
      executeThreshold: 0.35,
      executeDamageMultiplier: 2.25,
    },
  ),
  gear('steel-helmet', 'Steel Helm', 'head', 'steel', { defence: 21, health: 10 }, 'Steel'),
  gear(
    'steel-armor',
    'Steel Armor',
    'armor',
    'steel',
    { defence: 67, health: 32 },
    'Steel',
    undefined,
    'A complete steel field harness forged for the harshest frontiers.',
  ),
  gear(
    'steel-shield',
    'Steel Bulwark',
    'offhand',
    'steel',
    { defence: 42, health: 14 },
    'Steel',
    undefined,
    undefined,
    'shield',
  ),
  gear('steel-pickaxe', 'Steel Pick', 'tool', 'steel', {}, 'Steel'),
  {
    ...gear('steel-smithing-hammer', 'Steel Smithing Hammer', 'tool', 'steel', {}, 'Steel'),
    source: 'Smithing · Anvil',
    description: 'A rare, carefully balanced hammer for fast and economical Anvil work.',
  },
  ...[
    ['rat-tail', 'Rat Tail', 'Training Grounds · Forest Rat'],
    ['tattered-hide', 'Tattered Hide', 'Training Grounds · Forest Rat'],
    ['goblin-scrap', 'Goblin Scrap', 'Training Grounds · Goblin Scavenger'],
    ['bat-wing', 'Bat Wing', 'Copper Hills · Cave Bat'],
    ['crab-shell', 'Crab Shell', 'Copper Hills · Stoneback Crab'],
    ['wolf-pelt', 'Wolf Pelt', 'Ironwood Pass · Grey Wolf'],
    ['bandit-token', 'Bandit Token', 'Ironwood Pass · Road Bandit'],
    ['rusted-emblem', 'Rusted Emblem', 'Ironwood Pass · Road Bandit'],
  ].map(([id, name, source]) => ({
    id,
    name,
    category: 'drop' as const,
    description: 'A curious field discovery with a story still waiting to be told.',
    source,
    stackable: true,
    rarity: 'uncommon' as const,
    presentation: { iconKey: 'creature-part', visualCategory: 'creature-part' },
  })),
  ...[
    ['coarse-boar-hide', 'Coarse Boar Hide', 'Stonehill · Rocky Foothills · Hill Boar', 'common'],
    ['boar-tusk', 'Boar Tusk', 'Stonehill · Rocky Foothills · Hill Boar', 'uncommon'],
    ['stonehill-bristle', 'Stonehill Bristle', 'Stonehill · Rocky Foothills · Hill Boar', 'uncommon'],
    ['stonewool-fleece', 'Stonewool Fleece', 'Stonehill · Rocky Foothills · Stonehide Ram', 'common'],
    ['ram-horn', 'Ram Horn', 'Stonehill · Rocky Foothills · Stonehide Ram', 'uncommon'],
    ['dense-hoof-fragment', 'Dense Hoof Fragment', 'Stonehill · Rocky Foothills · Stonehide Ram', 'uncommon'],
    ['crawler-carapace', 'Crawler Carapace', 'Stonehill · Abandoned Mine · Tunnel Crawler', 'common'],
    ['burrow-claw', 'Burrow Claw', 'Stonehill · Abandoned Mine · Tunnel Crawler', 'uncommon'],
    ['glow-sac', 'Glow Sac', 'Stonehill · Abandoned Mine · Tunnel Crawler', 'rare'],
    ['bent-pick-head', 'Bent Pick Head', 'Stonehill · Abandoned Mine · Forsaken Miner', 'common'],
    ['miners-badge', "Miner's Badge", 'Stonehill · Abandoned Mine · Forsaken Miner', 'uncommon'],
    ['blackened-lantern', 'Blackened Lantern', 'Stonehill · Abandoned Mine · Forsaken Miner', 'uncommon'],
    ['old-claim-token', 'Old Claim Token', 'Stonehill · Abandoned Mine · Forsaken Miner', 'rare'],
    ['harpy-feather', 'Harpy Feather', 'Stonehill · Mountain Pass · Cliff Harpy', 'common'],
    ['hooked-talon', 'Hooked Talon', 'Stonehill · Mountain Pass · Cliff Harpy', 'uncommon'],
    ['windworn-pinion', 'Windworn Pinion', 'Stonehill · Mountain Pass · Cliff Harpy', 'uncommon'],
    ['cliff-nest-trinket', 'Cliff Nest Trinket', 'Stonehill · Mountain Pass · Cliff Harpy', 'rare'],
    ['marauder-insignia', 'Marauder Insignia', 'Stonehill · Mountain Pass · Stonehill Marauder', 'common'],
    ['riveted-leather-scrap', 'Riveted Leather Scrap', 'Stonehill · Mountain Pass · Stonehill Marauder', 'common'],
    ['warband-token', 'Warband Token', 'Stonehill · Mountain Pass · Stonehill Marauder', 'uncommon'],
    ['notched-whetstone', 'Notched Whetstone', 'Stonehill · Mountain Pass · Stonehill Marauder', 'rare'],
    ['sentinel-plate-fragment', 'Sentinel Plate Fragment', 'Stonehill · Ruined Watchtower · Ironbound Sentinel', 'common'],
    ['rusted-gear', 'Rusted Gear', 'Stonehill · Ruined Watchtower · Ironbound Sentinel', 'common'],
    ['runed-rivet', 'Runed Rivet', 'Stonehill · Ruined Watchtower · Ironbound Sentinel', 'uncommon'],
    ['watchtower-core', 'Watchtower Core', 'Stonehill · Ruined Watchtower · Ironbound Sentinel', 'rare'],
    ['captains-sigil', "Captain's Sigil", 'Stonehill · Ruined Watchtower · Watchtower Captain', 'common'],
    ['watchtower-key-fragment', 'Watchtower Key Fragment', 'Stonehill · Ruined Watchtower · Watchtower Captain', 'uncommon'],
    ['commanders-strap', "Commander's Strap", 'Stonehill · Ruined Watchtower · Watchtower Captain', 'uncommon'],
    ['old-garrison-seal', 'Old Garrison Seal', 'Stonehill · Ruined Watchtower · Watchtower Captain', 'rare'],
  ].map(([id, name, source, rarity]) => ({
    id,
    name,
    category: 'drop' as const,
    description: 'A Stonehill field discovery recovered from the old roads and ruins.',
    source,
    stackable: true,
    rarity: rarity as 'common' | 'uncommon' | 'rare',
    presentation: { iconKey: 'creature-part', visualCategory: 'creature-part' },
  })),
];

export const itemById = Object.fromEntries(ITEMS.map((item) => [item.id, item])) as Record<
  string,
  ItemDefinition
>;
